version: "3.7"

services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        ports: 
            - '30074:80'
        volumes: 
            - ./:/var/www/html

